# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manwang's Therapy
email: rotc39@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  잠시 하던 일을 멈추고 생각을 정리할 때 들여다 보세요.
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sjmw1030.github.io" # the base hostname & protocol for your site

#sidebar
default-image: /imgages/about_link.png
##webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: Manwang

copyright:
   name: Eden Koo
   link: 'http://sjmw1030.blog.me'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
##disqus: yes
##disqus-shortname: webjeda-demo

#social
facebook: http://facebook.com/manwang.koo
twitter: http://twitter.com/@manwangkoo
github: http://github.com/sjmw1030
email: rotc39@gmail.com

#facebook like box
fb-like-box: yes
fb-app-id: 713916212280026
fb-page-url: https://www.facebook.com/manwang.koo/
fb-page-title: Manwang's Facebook

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

